### ISSUE TITLE
Dropping support for Python 2.7

### ISSUE THREAD

**Issue by JKRhb** [agmangas/wot-py#23]
As Python 2.7 is now EOL, it should be considered to drop both the support and the testing in the CI for this version. This should make the code easier to maintain and further develop as dependencies like `six` could be removed.

**Comment by agmangas** [comment]
Agreed! 👍 

I was planning on dropping Python 2.7 and rewriting all asynchronous code to use `async def` instead of Tornado coroutines in the next major release.

**Comment by JKRhb** [comment]
I think with the addition of commit 99c80d5, this issue can now be closed :) Feel free to reopen it otherwise.
